services:
    mongodb:
        image: "mongo"
        container_name: mongodb
        volumes:
            - goals-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
    backend:
        build: ./backend
        container_name: backend
        ports:
            - "80:80"
        volumes:
            - logs:/app/logs
            - /app/node_modules
            - ./backend:/app
        env_file:
            - ./env/backend.env
        depends_on:
            - mongodb
    frontend:
        build: ./frontend
        container_name: frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/app/src
        stdin_open: true
        tty: true
        depends_on:
            - backend

volumes:
    goals-data:
    logs:
